server:
  port: 8082

spring:
  application:
    name: ms-pedidos

seguridad:
  emisores: ${SEGURIDAD_EMISORES:http://localhost:9000}

servicios:
  productos-url: ${PRODUCTOS_URL:http://localhost:8081}
